---
github:
  repository_url: https://github.com/davidselassie/games
collections:
  games:
      output: true
      permalink: :collection/:title:output_ext  # Permalink should use pretty title.
defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: game
